"""Add img_path field to product table

Revision ID: 780109746f8f
Revises: 6f6867f4b2a8
Create Date: 2025-05-05 15:30:38.018967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780109746f8f'
down_revision = '6f6867f4b2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###
