"""Add merchant_id to PriceData

Revision ID: c2364fac0f8a
Revises: e64c7a46c777
Create Date: 2025-05-08 17:35:34.175758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2364fac0f8a'
down_revision = 'e64c7a46c777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_price_data_merchant_id', 'merchant', ['merchant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###
