"""Refactor img_path field to image_url in Product table

Revision ID: e64c7a46c777
Revises: 780109746f8f
Create Date: 2025-05-07 16:54:09.200270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64c7a46c777'
down_revision = '780109746f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
